name: Trigger auto deployment for container-app-f6du2bkyh7efk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'api/**'
    - '.github/workflows/container-app-f6du2bkyh7efk-AutoDeployTrigger-f0005e12-8003-4342-a841-545b4a846855.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPF6DU2BKYH7EFK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPF6DU2BKYH7EFK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPF6DU2BKYH7EFK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPF6DU2BKYH7EFK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPF6DU2BKYH7EFK_REGISTRY_PASSWORD }}
          containerAppName: container-app-f6du2bkyh7efk
          resourceGroup: taskmanagementsystem94e5
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


